# Generated by Django 6.1.1 on 2026-09-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('project', 'payment_month'), name='unique_project_payment_month'),
        ),
    ]
