# Generated by Django 6.1.1 on 2026-09-11 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('client_address', models.TextField(blank=True)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_contact', models.CharField(blank=True, max_length=50)),
                ('platform', models.CharField(max_length=100)),
                ('status', models.CharField(default='NEW', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outcome_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
                ('outcome_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_outcomes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
