# Generated by Django 6.1.1 on 2026-09-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('SOLD', 'Sold'), ('NO_SALE', 'No Sale')], default='NEW', max_length=20),
        ),
    ]
