# Generated by Django 6.1.1 on 2026-09-17 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_alter_commission_percentage'),
        ('payments', '0003_payment_payment_amount_positive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='commission',
            name='recipient_role',
            field=models.CharField(choices=[('BD', 'Business Developer'), ('MANAGER', 'Manager')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='commission',
            constraint=models.UniqueConstraint(fields=('payment', 'recipient_role'), name='unique_payment_recipient_role'),
        ),
    ]
