# Generated by Django 6.1.1 on 2026-09-17 15:45

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_alter_commission_percentage_and_more'),
        ('payments', '0003_payment_payment_amount_positive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='commission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('percentage', Decimal('1.00')), ('recipient_role', 'BD')), models.Q(('percentage', Decimal('12.00')), ('recipient_role', 'MANAGER')), _connector='OR'), name='commission_percentage_by_role'),
        ),
    ]
