# Generated by Django 6.1.1 on 2026-09-17 17:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_commission_commission_percentage_by_role'),
        ('payments', '0003_payment_payment_amount_positive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('BD', 'Business Developer'), ('MANAGER', 'Manager')], max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='commission',
            name='commission_percentage_by_role',
        ),
        migrations.AddField(
            model_name='commissionrate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_commission_rates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commission',
            name='commission_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='commissions.commissionrate'),
        ),
        migrations.AddConstraint(
            model_name='commission',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='commission_amount_positive'),
        ),
        migrations.RemoveField(
            model_name='commission',
            name='percentage',
        ),
        migrations.AddConstraint(
            model_name='commissionrate',
            constraint=models.UniqueConstraint(fields=('role', 'effective_from'), name='unique_commission_rate_start'),
        ),
        migrations.AddConstraint(
            model_name='commissionrate',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='valid_commission_rate_period'),
        ),
        migrations.AddConstraint(
            model_name='commissionrate',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('role',), name='one_open_commission_rate_per_role'),
        ),
    ]
