# Generated by Django 6.1.1 on 2026-09-17 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0005_commissionrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='commission_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='commissions.commissionrate'),
        ),
    ]
