# Generated by Django 6.1.1 on 2026-09-19 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissions", "0006_alter_commission_commission_rate"),
        ("payments", "0003_payment_payment_amount_positive"),
        ("users", "0002_alter_user_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commissionrate",
            options={"ordering": ["role_id", "-effective_from"]},
        ),
        migrations.RemoveConstraint(
            model_name="commission",
            name="unique_payment_recipient_role",
        ),
        migrations.RemoveConstraint(
            model_name="commissionrate",
            name="valid_commission_rate_period",
        ),
        migrations.RemoveConstraint(
            model_name="commissionrate",
            name="one_open_commission_rate_per_role",
        ),
        # The old role field was a text field.
        # The database has been flushed, so we can safely remove it
        # and create the new ForeignKey field.
        migrations.RemoveField(
            model_name="commissionrate",
            name="role",
        ),
        migrations.AddField(
            model_name="commissionrate",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commission_rates",
                to="users.role",
            ),
        ),
        migrations.AddConstraint(
            model_name="commission",
            constraint=models.UniqueConstraint(
                fields=("payment", "commission_rate", "recipient"),
                name="unique_payment_rate_recipient",
            ),
        ),
        migrations.AddConstraint(
            model_name="commissionrate",
            constraint=models.CheckConstraint(
                condition=models.Q(("percentage__gt", 0)),
                name="commission_rate_percentage_positive",
            ),
        ),
        migrations.RemoveField(
            model_name="commission",
            name="recipient_role",
        ),
        migrations.RemoveField(
            model_name="commissionrate",
            name="effective_to",
        ),
    ]
